name = "aoc"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 0.13.0 and < 1.0.0"
gleam_community_maths = ">= 1.1.1 and < 2.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gladvent = ">= 2.0.2 and < 3.0.0"
gleeunit = ">= 1.0.0 and < 2.0.0"


[gladvent.2023.5]
pt_1 = 525792406
pt_2 = 79004094

[gladvent.2023.6]
pt_1 = 800280
pt_2 = 45128024

[gladvent.2023.7]
pt_1 = 249390788
pt_2 = 248750248

[gladvent.2023.8]
pt_1 = 20221
pt_2 = 14616363770447

[gladvent.2023.9]
pt_1 = 1861775706
pt_2 = 1082

[gladvent.2023.10]
pt_1 = 6786
pt_2 = 495

[gladvent.2023.11]
pt_1 = 9563821
pt_2 = 827009909817

[gladvent.2023.12]
pt_1 = 7286
pt_2 = 25470469710341

[gladvent.2023.13]
pt_1 = 35232
pt_2 = 37982

[gladvent.2023.14]
pt_1 = 105003
pt_2 = 93742

[gladvent.2023.15]
pt_1 = 511416
pt_2 = 290779

[gladvent.2024.1]
pt_1 = 2580760
pt_2 = 25358365

[gladvent.2024.2]
pt_1 = 202
pt_2 = 271

[gladvent.2024.3]
pt_1 = 173785482
pt_2 = 83158140


[gladvent.2024.4]
pt_1 = 2573
pt_2 = 1850
